name: Backup

on:
    workflow_dispatch:

env:
    DEBUG: ${{ vars.DEBUG }}

jobs:
    backup:
        name: MongoDB Backup
        runs-on: ubuntu-latest

        steps:
            - name: backup
              env:
                DOCKER_COMPOSE: ${{ secrets.DOCKER_COMPOSE }}
                ENV: ${{ secrets.ENV }}
              run: |
                echo "$DOCKER_COMPOSE" > docker-compose.yml
                echo "$ENV" > .env 
                docker compose up