name: Tests deployment script

on:
    # push:
    #     branches:
    #         - main
    workflow_dispatch:


env:
    DEBUG: ${{ vars.DEBUG }}

jobs:
    test-scrip:
        name: Test script
        runs-on: ubuntu-latest

        strategy:
            fail-fast: false
            matrix:
                cmd: ["featured-playlists", "categories", "artists", "recommendations"]

        steps:
            - name: Checkout Repo
              uses: actions/checkout@v3
              with:
                  repository: viper-adnan/lemonic-crawler
                  token: ${{ secrets.TOKEN }}

            - name: Setup Node.js
              uses: actions/setup-node@v3
              id: setup-node
              with:
                  cache: npm

            - name: Install dependencies
              run: |
                  npm install

            - name: Run test script
              env:
                  CONFIG: ${{ secrets.CONFIG }}
                  NODE_OPTIONS: --openssl-legacy-provider
              run: |
                  npm run scrape ${{ matrix.cmd }}
