name: Tests deployment script

on:
    push:
        branches:
            - main
    workflow_dispatch:
    schedule:
       - cron: "30 5 * * *"


env:
    DEBUG: ${{ vars.DEBUG }}

jobs:
    test-scrip:
        name: Test script
        runs-on: ubuntu-latest

        strategy:
            fail-fast: false
            matrix:
                cmd: ["playlists", "categories", "artists", "shuffle"]

        steps:
            - name: Run scraper
              run:
                  docker run -tq -e CONFIG_URL="$CONFIG_URL" $IMAGE_NAME scraper ${{ matrix.cmd }}
