name: Tests deployment script

on:
    push:
        branches:
            - main
    workflow_dispatch:
    schedule:
       - cron: "30 5 * * *"
    #     - cron: "*/20 * * * *"
    #     - cron: "*/30 * * * *"

env:
    DEBUG: ${{ vars.DEBUG }}

jobs:
    test-scrip:
        name: Test script
        runs-on: ubuntu-latest
        steps:
            - name: Checkout Repo
              uses: actions/checkout@v3
              with:
                  repository: enginegh/pages-cdn

            - name: Setup Node.js
              uses: actions/setup-node@v3
              id: setup-node
              with:
                  cache: npm

            - name: Install dependencies
              run: |
                  npm install

            - name: Run test script
              env:
                  CONFIG: ${{ secrets.CONFIG }}
                  NODE_OPTIONS: --openssl-legacy-provider
              run: |
                  npm run scrape categories 
