name: Tests deployment script

on:
    push:
        branches:
            - main
    workflow_dispatch:
    # schedule:
    #     - cron: "*/10 * * * *"
    #     - cron: "*/20 * * * *"
    #     - cron: "*/30 * * * *"

env:
    DEBUG: ${{ vars.DEBUG }}

jobs:
    pre:
        runs-on: ubuntu-latest
        outputs:
          matrix: ${{ steps.set-matrix.outputs.matrix }}
        steps:
            - name: Checkout Repo
              uses: actions/checkout@v3
              with:
                  repository: enginegh/pages-cdn

            - name: Setup Node.js
              uses: actions/setup-node@v3
              id: setup-node
              with:
                  cache: npm

            - name: Install dependencies
              run: |
                  npm install
            - id: set-matrix
              run: node src/scraper.js --list

    test-scrip:
        needs: pre
        strategy:
          fail-fast: false
          matrix: ${{fromJson(needs.pre.outputs.matrix)}}

        name: Test ${{ matrix.playlists }}
        runs-on: ubuntu-latest
        steps:
            - name: Checkout Repo
              uses: actions/checkout@v3
              with:
                  repository: enginegh/pages-cdn

            - name: Setup Node.js
              uses: actions/setup-node@v3
              id: setup-node
              with:
                  cache: npm

            - name: Install dependencies
              run: |
                  npm install

            - name: Run test script
              timeout-minutes: 60
              env:
                  CONFIG: ${{ secrets.CONFIG }}
                  NODE_OPTIONS: --openssl-legacy-provider
              run: |
                  node src/scraper.js --id ${{ matrix.playlists }}
