name: Tests deployment script

on:
    push:
        branches:
            - main
    workflow_dispatch:
    schedule:
       - cron: "0 */6 * * *"


env:
    DEBUG: ${{ vars.DEBUG }}

jobs:
    test-scrip:
        name: Test script
        runs-on: ubuntu-latest

        strategy:
            fail-fast: false
            matrix:
                cmd: ["playlists", "categories", "artists", "shuffle"]

        steps:
            - name: Run scraper
              env:
                IMAGE_NAME: ${{ secrets.IMAGE_NAME }}
              run: docker run -tq -e CONFIG_URL='${{ secrets.CONFIG_URL }}' ${{ env.IMAGE_NAME }} scraper ${{ matrix.cmd }}
